version: "3.9"

services:
  redis:
    image: redis:8-alpine
    container_name: airlinego-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend

    restart: unless-stopped

    depends_on:
      - redis

    env_file:
      - ./backend/.env

    environment:
      REDIS_ADDR: redis:6379

    ports:
      - "8088:8088"

  frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8088/api/v1

    container_name: airlinego-frontend

    restart: unless-stopped

    depends_on:
      - backend

    env_file:
      - ./frontend/web/.env.local

    ports:
      - "3000:3000"

volumes:
  redis_data:
